version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: coffee-api-postgres
    environment:
      POSTGRES_DB: coffee_db
      POSTGRES_USER: coffee_user
      POSTGRES_PASSWORD: coffee_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coffee_user -d coffee_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
